packages:
  - 'class_component'
  - 'context'
  - 'countdown'
  - 'from_zero_build'
  - 'own_react'
  - 'prove_react_17_vite'
  - 'prove_react_18_vite'
  - 'prove_react_19_vite'
  - 'strict_mode'
  - 'tp_jotai_farm'
  - 'tp_mobx_farm'
  - 'tp_react_router_farm'
  - 'tp_redux_farm'
  - 'tp_valtio_farm'
  - 'tp_zustand_farm'
  - 'version_18'

# tp mean third-party
