packages:
  - 'class_component'
  - 'context'
  - 'countdown'
  - 'from_zero_build'
  - 'own_react'
  - 'prove_react_17'
  - 'strict_mode'
  - 'tp_jotai'
  - 'tp_mobx'
  - 'tp_react_router'
  - 'tp_redux'
  - 'tp_valtio'
  - 'tp_zustand'
  - 'version_18'

# tp mean third-party
